version: "2"
services:
  good_news:
    build: .
    image: good_news
    ports:
      - 80:80
    environment:
      Database__MySqlSettings__ConnectionString: ${DB_CONNECTION_STRING}
  mysql:
    image: "mysql:5.7"
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_USER: "root"
    volumes:
      - my-datavolume:/var/lib/mysql
volumes:
  my-datavolume:
    driver: local
