version: "2"
services:
  good_news:
    build: .
    image: good_news
    ports:
      - 5005:80
    environment:
      Database__PostgresSettings__ConnectionString: ${Database__PostgresSettings__ConnectionString}
  
  postgres:
      image: postgres:alpine
      ports:
        - 5432:5432
      environment: 
        POSTGRES_PASSWORD: "secret"
        POSTGRES_USER: "good_news"
        POSTGRES_DB: "good_news"
      volumes:
        - postgres:/var/lib/postgresql
  
volumes:
  postgres:
