version: "3.1"
services:
  good_news:
    build: .
    image: good_news
    ports:
      - 5005:80
    environment:
      Database__PostgresSettings__ConnectionString: ${Database__PostgresSettings__ConnectionString}
  
  postgres:
      image: postgres:alpine
      ports:
        - 5432:5432
      environment: 
        POSTGRES_PASSWORD: "secret"
        POSTGRES_USER: "good_news"
        POSTGRES_DB: "good_news"
      volumes:
        - postgres:/var/lib/postgresql
  
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongo:/data/db
  
volumes:
  postgres:
  mongo:
